#= require ./store
#= require_tree ./mixins
#= require_tree ./modules
#= require_tree ./objects
#= require_tree ./helpers
#= require_tree ./components
#= require_tree ./templates
#= require_tree ./libs
#= require ./router
#= require_self
